apiVersion: apps/v1
kind: Deployment
metadata:
  name: retro
  labels:
    app: retro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retro
  template:
    metadata:
      labels:
        app: retro
    spec:
      containers:
      - name: retro
        image: maxrchung/retro
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: {{ .Values.nodeEnv }}
{{- if .Values.local }}
        volumeMounts:
        - mountPath: /app
          name: retro
      volumes:
        - name: retro
          hostPath:
            path: {{ .Values.hostPath }}
            type: Directory
{{- end }}