{{- if .Values.local }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retro
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: retro
            port:
              number: 3000
{{- end }}